# Docker version
version: "3"
# Container will be used
services:
  # Container name that be creted
  mongo:
    # Name container
    container_name: mongo-container
    # This container will come from this image
    # mongodb version 4
    image: mongo:4
    # Case down mongodb, restart him
    restart: always
    # Is array, persist the data, from data to data/db docker
    volumes:
      - ./data:/data/db
    # Mapping port from mongodb local to mongodb docker
    ports:
      - "27017:27017"
  # Up clean-node-api
  api:
    container_name: api-container
    # Informs Dockerfile way, that generates are image
    build: .
    # When build exists, to name the container use the image tag
    image: clean-node-api
    restart: always
    command: npm run start
    # WORKDIR path of project build
    volumes:
      - ./dist:/usr/src/clean-node-api
    ports:
      - "3333:3333"
    # Link access api with mongo
    links:
      - mongo
