# Docker version
version: "3"
# Container will be used
services:
  # Container name that be creted
  mongo:
    # Container name
    container_name: mongo-container
    # This container will come from this image
    # mongodb version 4
    image: mongo:4
    # Case down mongodb, restart him
    restart: always
    # Is array, persist the data, from data to data/db docker
    volumes:
      - ./data:/data/db
    # Mapping port from mongodb local to mongodb docker
    ports:
      - "27017:27017"
  # Up clean-node-api
  api:
    container_name: api-container
    # Docker node version
    image: node:14
    # local dir from project
    working_dir: /usr/src/clean-node-api
    restart: always
    # Install only production dependencies and before run debug (on final)
    command: bash -c "npm install --only=prod && npm run debug"
    # WORKDIR path of project build
    volumes:
      # The last "/" means that whatever is fixed, as in the
      # container's dist
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    # Link access api with mongo
    links:
      - mongo
