import {
  accountSchema,
  accountEditParamsSchema,
  loginParamsSchema,
  signUpParamsSchema,
  errorSchema,
  surveySchema,
  surveysSchema,
  surveyAnswerSchema,
  addSurveyAnswerSchema,
  addSurveyParamsSchema,
  saveSurveyParamsSchema,
  surveyResultSchema,
  surveyResultAnswerSchema,
  refreshTokenParamsSchema,
  refreshTokenSchema,
} from './schemas/';

export default {
  account: accountSchema,
  accountEditParams: accountEditParamsSchema,
  loginParams: loginParamsSchema,
  signUpParams: signUpParamsSchema,
  refreshToken: refreshTokenSchema,
  refreshTokenParams: refreshTokenParamsSchema,
  error: errorSchema,
  survey: surveySchema,
  surveys: surveysSchema,
  surveyAnswer: surveyAnswerSchema,
  addSurveyAnswer: addSurveyAnswerSchema,
  addSurveyParams: addSurveyParamsSchema,
  saveSurveyParams: saveSurveyParamsSchema,
  surveyResult: surveyResultSchema,
  surveyResultAnswer: surveyResultAnswerSchema,
};
